### ISSUE TITLE
有木有java的使用Demo案例?

### ISSUE THREAD

**Issue by ILoveLin** [jenly1314/ASocket#3]
有木有java的使用Demo案例?大佬更新一波呗

**Comment by jenly1314** [comment]
> 有木有java的使用Demo案例?大佬更新一波呗

* ASocket的基本使用步骤比较明确：创建一个实例，设置监听，启动连接，发送消息。
* kotlin跟java的语法很类似，应该很容易看懂的。

**Comment by ILoveLin** [comment]
好吧 谢谢


| |
tongzhengtong
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月24日 16:11 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jenly1314/ASocket] 有木有java的使用Demo案例? (Issue #3) |

有木有java的使用Demo案例?大佬更新一波呗

ASocket的基本使用步骤比较明确：创建一个实例，设置监听，启动连接，发送消息。
kotlin跟java的语法很类似，应该很容易看懂的。
